pipeline:
  name: pipe
  identifier: pipe
  tags: {}
  template:
    templateRef: pipeline_temp
    versionLabel: V1
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      stages:
        - stage:
            identifier: testStage
            template:
              templateInputs:
                type: CI
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: Run_2
                          type: Run
                          spec:
                            connectorRef: <+input>
                            image: <+input>
                            shell: <+input>
                  infrastructure:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                      namespace: <+input>
  projectIdentifier: palak_labs
  orgIdentifier: default
