pipeline:
  name: gitex-admin
  identifier: gitexadmin
  projectIdentifier: palak_labs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test-stage
        identifier: teststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: qsahbasbjas
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
