pipeline:
  name: palak_test_git
  identifier: palak_test_git
  projectIdentifier: palak_labs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cystom
        identifier: cystom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "test"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
