pipeline:
  name: test_pipe
  identifier: test_pipe
  projectIdentifier: palak_labs
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "hello"

                          microdnf install -y nmap-ncat
                          nc -h

                          nc -zv 172.31.19.78 3389
                          nc -zv 172.31.19.78 5985
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - docker-delegate
                  timeout: 10m
        tags: {}
  orgIdentifier: default
