pipeline:
  name: test_pipe
  identifier: test_pipe
  projectIdentifier: palak_labs
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "hello"

                          curl -v http://172.31.19.78:5985/wsman
                          # Test WinRM HTTP from Linux
                          curl -v http://ec2-3-129-60-224.us-east-2.compute.amazonaws.com:5985/wsman \
                            -H "Content-Type: application/soap+xml;charset=UTF-8"
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - docker-delegate
                  timeout: 10m
        tags: {}
  orgIdentifier: default
