apiVersion: harness.io/v1
kind: Component
type: website
identifier: artistreact
name: artist-react
owner: user:account/palak.raina@harness.io
orgIdentifier: default
projectIdentifier: bootcampcipalak
spec:
  lifecycle: Production
  dependsOn:
  - component:account/custom_comp
metadata:
  annotations:
    backstage.io/techdocs-ref: value
  tags:
  - react
