apiVersion: harness.io/v1
kind: Component
type: website
identifier: artistreact
name: artist-react
owner: user:account/palak.raina@harness.io
orgIdentifier: default
projectIdentifier: bootcampcipalak
spec:
  lifecycle: Production
  sourceCode:
    provider: Github
    repoName: harness-labs
    connectorRef: account.ghallaccess
    branch: main
    monoRepo: false
    url: https://github.com/palakRaina-devops/harness-labs/tree/main
    dependsOn:
    - component:account/custom_comp
    system:
    - system:account.default.bootcampcipalak/test-system
    partOf:
    - system:account.default.bootcampcipalak/test-system
  partOf:
  - system:account.default.bootcampcipalak/test-system
  dependsOn:
  - component:account/custom_comp
metadata:
  annotations:
    backstage.io/techdocs-ref: value
  tags:
  - react
